_user_bundle:
    resource: "@itawUserBundle/Resources/config/routing.yml"

itaw_backend:
    resource: "@itawBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

itaw_app:
    resource: "@itawAppBundle/Resources/config/routing.yml"
    prefix:   /
