backend_index:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: backend_dashboard, permanent: true }

backend_dashboard:
    pattern:  /dashboard
    defaults: { _controller: itawBackendBundle:Page:dashboard }

backend_endpoints:
    resource: "@itawBackendBundle/Resources/config/Endpoint/routing.yml"
    prefix:   /endpoints

backend_incidents:
    resource: "@itawBackendBundle/Resources/config/Incident/routing.yml"
    prefix:   /incidents
